version: '3.6'
services:  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d:ro
      - nginx-vhost:/etc/nginx/vhost.d:ro
      - nginx-html:/usr/share/nginx/html:ro
      - nginx-certs:/etc/nginx/certs:ro
    #labels:
      #com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - web_proxy

  nginx-docker-gen:
    image: jwilder/docker-gen
    container_name: nginx-docker-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - nginx-conf:/etc/nginx/conf.d:rw
      - nginx-vhost:/etc/nginx/vhost.d:ro
      - nginx-certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    #labels:
      #com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: "true"
    networks:
      - web_proxy

  letsencrypt-http:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-http
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-vhost:/etc/nginx/vhost.d:rw
      - nginx-html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-docker-gen

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:
  nginx-certs:

networks:
  web_proxy:
    name: web_proxy
